### ISSUE TITLE
NameError in sample_data.py

### ISSUE THREAD

**Issue by JEHoctor** [petrhruby97/learning_minimal#3]
Very nice paper. I enjoyed discussing this work with you at CVPR, and I'm keen to be able to reproduce your results. If anyone would like to follow my attempt to replicate this work, I have created [a branch on my fork](https://github.com/JEHoctor/learning_minimal/tree/replication-4p3v) where I will post extended readme information, instructions, `requirments.txt`, some light code clean-up, etc.

There is an undefined variable on line 15 of `sample_data.py`. This appears to affect both the 4p3v and 5p2v versions of the code, which contain identical versions of `sample_data.py`.

Here is the traceback:
```
Traceback (most recent call last):
  File "/home/james/Projects/learning_minimal/4p3v/sample_data.py", line 47, in <module>
    generate(input_folder, output_file, goal_samples)
  File "/home/james/Projects/learning_minimal/4p3v/sample_data.py", line 15, in generate
    print("generating " + name)
NameError: name 'name' is not defined
```

**Comment by petrhruby97** [comment]
Thank you for your interest in my work!

The line 15 is likely some artifact from a previous version of the code. Because the variable name does not appear anywhere else in the code, I believe that the best solution is to delete the line.

Petr

**Comment by JEHoctor** [comment]
I found that I also had an issue on lines 18 and 24, with the `mode` variable, but the solution was the same: just remove it. (I also had to remove the string `" 1 "` from the command strings). Here's my updated `sample_data.py` that is now working for me: https://github.com/JEHoctor/learning_minimal/blob/39bd400b5dc6d28f8146affd1eca945974787dd4/4p3v/sample_data.py I made some other minor changes, which shouldn't be necessary to get things to work.

By the way, how long does running `bin/anchors` take for you? It looks like it will take at least a few hours on my machine.

**Comment by petrhruby97** [comment]
You are right, the mode variable has the same issue as the name variable. 

Running bin/anchors usually takes much less for me, typically about one minute. Have you correctly executed the bin/connectivity binary first? How big is your MODEL/connectivity.txt file?

It may also be interesting to see, how does your file with sampled problem/solution pairs look like and how big it is. If the number of problem/solution pairs is about 40000, it may take more than one day to compute the connectivity graph. If you want to speed this up, you can generate fewer problem/solution pairs (about 10000), which should take much less (about an hour on a good machine), and the result should not be much worse.
